apiVersion: v1
kind: Namespace
metadata:
  name: fiap
  labels:
    name: fiap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: fiap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fiap
data:
  MIGRATIONS_DIR: "scripts/db/migrations"