apiVersion: v1
kind: Namespace
metadata:
  name: fiap
  labels:
    name: fiap
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: fiap
---
apiVersion: v1
kind: Secret
metadata:
  name: app-sc
  namespace: fiap
data:
  JWT_SECRET: SldUX1NFQ1JFVAo=
  POSTGRES_PASSWORD: X19QT1NUR1JFU19QQVNTV09SRF9fCg==
  POSTGRES_USER: X19QT1NUR1JFU19VU0VSX18K
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fiap
data:
  POSTGRES_DB: "oficina"
  SONAR_JDBC_USERNAME: "postgres"
  SONAR_JDBC_PASSWORD: "postgres"
  SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonarqube"
  PG_DSN: "postgres://postgres:postgres@db:5432/oficina?sslmode=disable"
  PORT: "8080"
  MIGRATIONS_DIR: "scripts/db/migrations"
  TEST_SEEDERS_DIR: "scripts/db/test_seeders"
  LOG_LEVEL: "debug"
  APP_ENV: "test"