apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fiap
data:
  POSTGRES_DB: "oficina"
  SONAR_JDBC_USERNAME: "postgres"
  SONAR_JDBC_PASSWORD: "postgres"
  SONAR_JDBC_URL: "jdbc:postgresql://db:5432/sonarqube"
  PG_DSN: "postgres://postgres:postgres@db:5432/oficina?sslmode=disable"
  PORT: "8080"
  MIGRATIONS_DIR: "scripts/db/migrations"
  TEST_SEEDERS_DIR: "scripts/db/test_seeders"
  LOG_LEVEL: "debug"
  APP_ENV: "test"
