apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-np
  name: svc-np
  namespace: fiap
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: appgo
  type: NodePort
