apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fiap-postgres
  namespace: fiap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fiap-postgres
  template:
    metadata:
      labels:
        app: fiap-postgres
    spec:
      volumes:
        - name: pgdata
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate
        - name: pgconf
          hostPath:
            path: /var/lib/postgresql/conf
            type: DirectoryOrCreate
        - name: pglogs
          hostPath:
            path: /var/lib/postgresql/logs
            type: DirectoryOrCreate
      containers:
        - name: fiap-postgres
          image: postgres:16
          envFrom :
            - secretRef:
                name: pgsecrets
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
            - name: pgconf
              mountPath: /var/lib/postgresql/conf
            - name: pglogs
              mountPath: /var/lib/postgresql/logs
          ports:
            - containerPort: 5432