name: Infrastructure CI/CD Pipeline

on:
  push:
    branches:
      - chore/base-structure # TODO: Change to main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.14.2
  ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}

jobs:
  sonar-scan:
    name: SonarCloud Security Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform-plan:
    name: Terraform Plan
    needs: sonar-scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tfplan_exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with: 
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@56d6a583f00f6bad6d19d91d53a7bc3b8143d0e9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ./infra

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./infra

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan \
            -var-file=inventories/${{ env.ENVIRONMENT }}/terraform.tfvars \
            -out=tfplan \
            -no-color \
            -detailed-exitcode || echo "exitcode=$?" >> $GITHUB_OUTPUT
        working-directory: ./infra

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v6
        with:
          name: tfplan-${{ env.ENVIRONMENT }}
          path: infra/tfplan
          retention-days: 5


  terraform-apply:
    name: Terraform Apply
    needs: [sonar-scan, terraform-plan]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    # TODO: Remove this comment when the branch is merged to main
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@56d6a583f00f6bad6d19d91d53a7bc3b8143d0e9
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init 
        run: terraform init
        working-directory: ./infra

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ env.ENVIRONMENT }}
          path: infra/

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply \
            -auto-approve tfplan
        working-directory: ./infra

