name: Terraform Apply

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: dev
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: true
    outputs:
      cluster_name:
        value: ${{ jobs.terraform-apply.outputs.cluster_name }}

env:
  AWS_REGION: us-east-1
  TF_VERSION: 1.14.2

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      cluster_name: ${{ steps.tf_outputs.outputs.cluster_name }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85
        with:
          terraform_version: ${{ env.TF_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Download Terraform Plan
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: tfplan-${{ inputs.environment }}
          path: infra/

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply \
            -auto-approve tfplan
        working-directory: ./infra

      - name: Extract Terraform Outputs
        id: tf_outputs
        run: |
          CLUSTER_NAME=$(terraform output -raw cluster_name)
          echo "cluster_name=${CLUSTER_NAME}" >> $GITHUB_OUTPUT
        working-directory: ./infra
